apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: platform-engineering
spec:
  containers:
    - name: nginx
      image: nginx:alpine
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: node.kubernetes.io/instance-type
            operator: In
            values:
              - c6a.large
